### ISSUE TITLE
App fails to start.

### ISSUE THREAD

**Issue by arbales** [nixme/warble#2]
Seems I'm missing a Redis configuration file. Perhaps the .sample will work…………

```
/Users/austin/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/syck.rb:145:in `initialize': No such file or directory - /Users/austin/Workspace/warble/config/redis.yml (Errno::ENOENT)
from /Users/austin/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/syck.rb:145:in `open'
from /Users/austin/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/syck.rb:145:in `load_file'
from /Users/austin/Workspace/warble/config/initializers/redis.rb:1:in `<top (required)>'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:235:in `load'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:235:in `block in load'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:235:in `load'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/engine.rb:201:in `block (2 levels) in <class:Engine>'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/engine.rb:200:in `each'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/engine.rb:200:in `block in <class:Engine>'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/initializable.rb:25:in `instance_exec'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/initializable.rb:25:in `run'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/initializable.rb:50:in `block in run_initializers'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/initializable.rb:49:in `each'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/initializable.rb:49:in `run_initializers'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/application.rb:134:in `initialize!'
from /Users/austin/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.5/lib/rails/application.rb:77:in `method_missing'
from /Users/austin/Workspace/warble/config/environment.rb:5:in `<top (required)>'
from <internal:lib/rubygems/custom_require>:29:in `require'
```

**Comment by arbales** [comment]
Actually, it seems you've excluded your redis config.

**Comment by nixme** [comment]
Indeed. You're supposed to copy the sample to redis.yml and put your own configuration in there. And I wouldn't mind you committing to master if you didn't undo my work (like removing the sample file). So I'm resetting the branch to what it was. Move your stuff to it's own branch and do a pull request for a merge.

**Comment by arbales** [comment]
luckily, everything is terrible

**Comment by dylan-conlin** [comment]
I don't know what you guys are talking about, but this helped me fix a similar problem I was having elsewhere. Thanks for this.
